### ISSUE TITLE
Conflict with /dev/input/eventN with other HID(Keyboard, etc.) attached 

### ISSUE THREAD

**Issue by koileLab** [meri-imperiumi/signalk-bluetooth-anchor-button#2]
Here some notes about the /dev/Input/ handling. 

I had I had to change the  `dev = InputDevice('/dev/input/event1') ` to `dev = InputDevice('/dev/input/event0')`in the listener.py because it is/was my only Input Device.

Harder to realize was the changing of the event numbers when I attach the USB Dongle for my wireless Keyboard with touchpad. It creates 4 InputEvents and so the Camkix button ended up to be /dev/input/event4 and stopped working.

Don't know if this can be handled in the Plugin, but I wanted to document it for other people to be aware of... In general you quite rarely attach/detach HID on a boat. But because you change it so rarely you'll probably have forgotten about the Input/Event Thingi...

It would be cool if we could address the device in a more deterministic manner or find another one which actually does.

**Comment by bergie** [comment]
I think it should be possible to give the device a persistent name via udev rules. Would need some investigation
